spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdata
    username: hachicore
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true